Session 3: Lifecycle
laiug787/ios-training-laiug787-WeatherApp pull request #3
Opened 2023-09-05 06:22 UTC by laiug787

## 概要
インターン課題
お天気アプリのビューのライフサイクルを理解

### 課題URL
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/VC_Lifecycle.md

### 変更点概略
・Main.storyboardの名称変更
・inital View をLaunchViewに変更
・`viewDidAppear` `viewDidLayoutSubviews`を用いて実装

| 変更後 |
| ------------- |
| <img height="500" src="https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/assets/86225588/d4640f5e-50bb-4907-9e2d-6163ce1fb1c7">  |

2023-09-06 04:02 UTC, laiug787 commented
コンフリクトを解消いたしました。
初めてのコンフリクト解消作業でとても知見が広がりました。

2023-09-06 04:14 UTC, laiug787 commented
session 2 のマージをレビュー完了前に提出してしまったため、その修正をします。もう少々お待ちください。

2023-09-06 05:30 UTC, laiug787 commented
修正完了いたしました。
ご確認お願いいたします。

2023-09-06 06:21 UTC, macneko-ayu commented on WhetherApp/WeatherManager.swift
📝 
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/2/files/3d505c8ed761d1ef09bf166ece425123009f979f#r1316611410
の指摘を修正

2023-09-06 06:22 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +private extension WeatherType {
📝 
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/2/files/3d505c8ed761d1ef09bf166ece425123009f979f#r1316602162
の指摘を修正

2023-09-06 08:00 UTC, macneko-ayu requested changes
mustの指摘は修正必須です。
その他はアドバイスに近いので次のPRで修正するか、修正なしでもOKです。
もしかしたら今後のSessionで治すことになるかもですが

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +    var imageName: String {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
private extensionになっており他クラスなどから呼び出せないようになっているので、この実装でも悪くはないはないのですが、素直にViewControllerのメソッドを用意したほうがシンプルかなと思いました。
imageColorも同じく。

```swift
private extension WeatherViewController {
    func getImageName(for weatherType: WeatherType) -> String {
        switch weatherType {
        case .sunny:
            return "whether-sunny"
        case .cloudy:
            return "whether-cloudy"
        case .rainy:
            return "whether-rainy"
        }        
    }
}
```

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/LaunchView.storyboard
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
突き詰めるとViewではあるのですが、`LaunchScreen` のほうが命名の粒度が適切だと思いました。
iOSのプロジェクトテンプレートが `LaunchScreen` となっているので、合わせると意図が伝わりやすいです。
また、 `Launch` だけでもいいかも

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/LaunchViewController.swift
> +    override func viewDidLoad() {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
overrideするだけなら不要です

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/LaunchViewController.swift
> +        let storyboard = UIStoryboard(name: "WeatherView", bundle: nil)
![must-badge](https://img.shields.io/badge/review-must-red.svg)
画面遷移処理がviewDidAppearとviewDidLayoutSubviewsで重複しているため、コンソールにログが出力されています。

```
2023-09-06 16:23:44.748834+0900 WhetherApp[17809:8695386] Unbalanced calls to begin/end appearance transitions for <WhetherApp.LaunchViewController: 0x116705240>.
```

viewDidLayoutSubviewsはドキュメントに記載のあるようにViewのレイアウトの調整を行うときに利用するもので、画面遷移に使うことはほとんどないと思います

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/WeatherManager.swift
> +final class WeatherManager {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
Managerと命名するといろいろな役割をもちかねないので、避けたほうがよいです。

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/WeatherManager.swift
> +    static var instance = WeatherManager()
![must-badge](https://img.shields.io/badge/review-must-red.svg)
シングルトンにしたかったのかなと推測したのですが、現状は他からインスタンスが生成できてしまいます。
`private init() {}` を実装することで、他からインスタンス生成できなくなります。

2023-09-06 08:00 UTC, macneko-ayu commented on WhetherApp/WeatherManager.swift
📝 
手法にもよるのですが、私はテストコードを書くときにWeatherRepositoryProtocolに準拠させたMockを用意することで実際に通信を行わずにテストが可能になるなどの理由から、以下のように実装することが多いです。

```swift
protocol WeatherRepositoryProtocol {
    func fetchWeatherCondition() -> String
}

struct WeatherRepository: WeatherRepositoryProtocol {
    func fetchWeatherCondition() -> String {
        YumemiWeather.fetchWeatherCondition()
    }
}
```

2023-09-06 08:32 UTC, laiug787 commented on WhetherApp/WeatherManager.swift
> +final class WeatherManager {
分かりました。

2023-09-06 08:36 UTC, laiug787 commented on WhetherApp/WeatherManager.swift
> +    static var instance = WeatherManager()
実装いたしました。

2023-09-06 08:51 UTC, laiug787 commented on WhetherApp/WeatherManager.swift
参考例をありがとうございます。
次のAPI関連の課題で参考にさせていただきます。

2023-09-06 08:51 UTC, laiug787 commented on WhetherApp/LaunchViewController.swift
> +    override func viewDidLoad() {
承知しました。

2023-09-06 08:53 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +    var imageName: String {
修正いたしました。
仰ることを理解しました。

2023-09-06 08:55 UTC, laiug787 commented on WhetherApp/LaunchView.storyboard
ありがとうございます。
今後のPRで修正してみます。

2023-09-06 09:01 UTC, laiug787 commented on WhetherApp/LaunchViewController.swift
> +        let storyboard = UIStoryboard(name: "WeatherView", bundle: nil)
なるほど、コンソールのログの意味が分からなかったのですが、理解しました。
確かにviewDidLayoutSubviews()は必要ないですね。
viewDidAppearを実装した後に修正することと課題の欄に出てきたワードとして気を取られすぎてました。

2023-09-06 09:07 UTC, laiug787 commented
修正しました。

2023-09-06 13:50 UTC, ykws commented on WhetherApp/LaunchViewController.swift
> +        self.present(nextVC, animated: true, completion: nil)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

下記のように関数に定義されている default value と同じ値を設定する場合は省略可能です。

> completion: (() -> [Void](https://developer.apple.com/documentation/swift/void))? = nil

- 🔖 [Default Parameter Values](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/functions#Default-Parameter-Values)
- 🔖  [present(_:animated:completion:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-present)

2023-09-06 13:50 UTC, ykws commented on WhetherApp/LaunchViewController.swift
> +        self.present(nextVC, animated: true, completion: nil)
```suggestion
        self.present(nextVC, animated: true)
```

2023-09-06 13:50 UTC, ykws commented on WhetherApp/WeatherViewController.swift
> +        self.dismiss(animated: true, completion: nil)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

present と同様に dismiss も

```suggestion
        self.dismiss(animated: true)
```

🔖 [dismiss(animated:completion:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss)

2023-09-06 13:50 UTC, ykws commented on WhetherApp/WeatherViewController.swift
> +private extension WeatherViewController {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

WeatherType の extension として computed property で簡潔に表現することも可能です。

🔖 [[Swift] FunctionとComputed Propertyの使い分けの基準](https://qiita.com/k-yamada-github/items/fb4da8bbb4de2f4d7b54)

2023-09-06 13:50 UTC, ykws commented on WhetherApp/WeatherViewController.swift
> +            return "whether-sunny"
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

リソース名の方ですが typo ですね。 cloudy, rainy も同様でした。

```suggestion
            return "weather-sunny"
```

2023-09-06 13:50 UTC, ykws commented on WhetherApp/WeatherRepository.swift
> +    private let request = YumemiWeather.self
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

`YumemiWeather` が `request` なのも引っかかる感じがします。
コメント追記しました。

> `YumemiWeather` なので `yumemiWeather` で良い気がしました。

- https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/2#discussion_r1315584768

2023-09-06 13:50 UTC, ykws commented on WhetherApp/WeatherRepository.swift
> +    func fetchWeatherCondition() -> WeatherType {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

`WeatherType` を返すなら、せっかく Wrapper なのでそのように命名したいですね

```suggestion
    func fetchWeatherType() -> WeatherType {
```

2023-09-06 13:50 UTC, ykws commented on WhetherApp/WeatherRepository.swift
> +    static var instance = WeatherRepository()
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

この class をシングルトンにしたい動機は何でしょうか？

2023-09-06 13:53 UTC, ykws commented on WhetherApp/WeatherViewController.swift
> +private extension WeatherViewController {
afa90d5470ec2ece19f0d5365f48e99854df0f5c にて元々 `extension WeatherType` だったのを書き換えたんですね

- https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/3#discussion_r1316795697

2023-09-07 00:42 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +    var imageName: String {
typoはありますが（気づいていなかった🙏）、指摘自体は直っていました！

2023-09-07 00:47 UTC, macneko-ayu commented on WhetherApp/LaunchViewController.swift
> +        let storyboard = UIStoryboard(name: "WeatherView", bundle: nil)
ライフサイクルメソッドに実装する処理のセオリーみたいなものが存在するので、公開されているコード（OSS）やドキュメントを見るなどして知識を蓄えると今後役立ちそうです。

2023-09-07 00:50 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +private extension WeatherViewController {
好みもあると思うのですが、たとえばViewModel内にWeatherTypeが定義されている場合は「WeatherType の extension として computed property で簡潔に表現」という形をとるかなと思います。
今回はVM層もないし、Viewに依存しないほうがいいかなと思い、ViewControllerにメソッドを用意する形を提案しました。

2023-09-07 00:51 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +    func fetchWeatherCondition() -> WeatherType {
私の例示したコードが… 😇

2023-09-07 00:52 UTC, macneko-ayu submitted a review, later dismissed
私が指摘した箇所は修正されていたので、Approveします。

2023-09-07 01:22 UTC, laiug787 commented on WhetherApp/LaunchViewController.swift
> +        self.present(nextVC, animated: true, completion: nil)
確かに、デフォルト値をわざわざ入力すると勘繰ってしまいますね。
ありがとうございます。
Suggested changeでコミットできるのを初めて知りました。

2023-09-07 01:32 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +private extension WeatherViewController {
> 引数なしのFunctionを使うかComputed Propertyを使うかで迷う

@ykws 
とても迷う事があります。計算が多いかどうかで判断してます。

@macneko-ayu 
UIKitの使用範囲をViewController内に留めるのはとても納得です。

2023-09-07 01:34 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +            return "whether-sunny"
お恥ずかしい限りです。
プロジェクト名もtypoで、穴があったら入りたいです。
修正いたします。

2023-09-07 01:39 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    private let request = YumemiWeather.self
リンク先確認しました。
修正します。

2023-09-07 01:58 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    static var instance = WeatherRepository()
CoreDataを扱いで見慣れていたのでそうしました。
リポジトリパターンを調べてみると、命名と期待される役割が噛み合っていないように思えます。
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/3#discussion_r1316889085
次からのSession以降でAPI関連の機能を足したときに、どんな課題に直面するか・何が異なるのか見てみたいと思います。

2023-09-07 02:06 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    func fetchWeatherCondition() -> WeatherType {
@ykws @macneko-ayu 
ご指摘、ありがとうございます。
[YumemiWeather.fetchWeatherCondition()](https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweather/fetchweathercondition())
WeatherRepositoryのメソッド名は上記のAPIのメソッド名と揃えていて、`fetchWeatherType()`と名前を変更すると
今後、同様な役割を持つメソッド名が多発すると考え、このような命名をいたしました。

2023-09-07 02:11 UTC, laiug787 commented
改善できる箇所を修正・完了しました。

2023-09-07 05:11 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +    func fetchWeatherCondition() -> WeatherType {
その場合、WeatherTypeの命名をWeatherConditionに変えるというのもありですね

2023-09-07 05:15 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    func fetchWeatherCondition() -> WeatherType {
確かに、そうですね。
Session 5で`fetchXXXX() -> XXXX `のように揃えます。

2023-09-07 05:31 UTC, macneko-ayu commented
川島さんが質問されていますが、私もシングルトンである必要性がないと感じるので、Approve解除しました。
シングルトンはアプリケーション内であるクラスのインスタンスがひとつであることを保証したいときに用いるもので、今回の使い方には適していないです。
よくある使い方は「アプリケーション内であるクラスに保持した値をどこからでも参照、または更新したい」場合かなと思います。
「あるクラスのインスタンスごとに保持された値が異なると困るので、ひとつの値のインスタンスのみを参照・更新する必要がある」といった理由です。
今回実装したAPI通信処理では値を保持せず、かつ複数インスタンスが存在したところで問題はないので、シングルトンである必要はないです。

2023-09-07 05:52 UTC, laiug787 commented
@macneko-ayu 
分かりやすい説明をしてくださりありがとうございます。
> API通信処理では値を保持せず、かつ複数インスタンスが存在したところで問題はない

値を保持しないしないとという点でシングルトンである必要がないことに、納得いたしました。
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/3#discussion_r1316889085
を頼りに修正いたします。

2023-09-07 05:53 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    func fetchWeatherCondition() -> WeatherType {
今直します。

2023-09-07 06:05 UTC, laiug787 commented
修正しました。

2023-09-07 07:26 UTC, macneko-ayu approved these changes
修正ありがとうございました！

2023-09-07 09:03 UTC, laiug787 commented
@ykws ご確認お願いします。

2023-09-07 15:54 UTC, ykws approved these changes
全体的によく整理されて責務を分離して実装を進められていると感じました！

2023-09-07 15:54 UTC, ykws commented on WhetherApp/WeatherViewController.swift
> +    private let weatherAPI = WeatherRepository()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

weatherAPI と命名してしまうと weatherRepository の内部実装に関心が向いてしまうので、単に repository としておく方が、関心の分離ができている状態を維持できると思いました。

他の部分がよくできているので、特に気になりました。

2023-09-07 15:54 UTC, ykws commented on WhetherApp/WeatherViewController.swift
>          weatherImage.image = nil
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

weatherImage を非表示にするために nil を代入していると思いますが、 dismiss して ViewController が初期化されたら非表示になるため、明示的に nil を代入しなくても良さそうです。

2023-09-08 01:27 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +private extension WeatherViewController {
あ、私の説明ちょっと間違ってることに気づきました。
VMにはUIKit（View層）をimportしないというのが原則としてあるので、VMにextensionでUIImageを返す処理を記載するのはよくないか。

2023-09-08 02:11 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +    private let weatherAPI = WeatherRepository()
修正しました。

2023-09-08 02:12 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
>          weatherImage.image = nil
盲点でした。ありがとうございます。
修正しました。

2023-09-08 02:14 UTC, merged