[WIP] Session 4: Delegate
laiug787/ios-training-laiug787-WeatherApp pull request #4
Opened 2023-09-06 10:54 UTC by laiug787

## 概要
・deinitの実装
・delegateパターンを適用

### 課題URL
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md

### 変更点概略
・`deinit`成功時`"Deinitialize WeatherViewController"`を出力

```swift
deinit {
    print("Deinitialize WeatherViewController")
}
```
を追加

・ `WeatherViewDelegate`を作成、Delegateパターンに準拠
```swift
@IBAction private func closeAction(_ sender: Any) {
    weatherImage.image = nil
    self.dismiss(animated: true, completion: nil)
}

@IBAction private func reloadAction(_ sender: Any) {
    let weather = weatherAPI.fetchWeatherCondition()
    weatherImage.image = UIImage(named: weather.imageName)
    weatherImage.tintColor = weather.imageColor
}
```
の実装を
```swift
final class WeatherViewController: UIViewController {
    ...
    
    weak var delegate: WeatherViewDelegate?

    @IBAction private func closeAction(_ sender: Any) {
        delegate?.closeWeather()
    }
    
    @IBAction private func reloadAction(_ sender: Any) {
        delegate?.reloadWeather()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.delegate = self
    }
}

extension WeatherViewController: WeatherViewDelegate {
    func closeWeather() {
        weatherImage.image = nil
        self.dismiss(animated: true, completion: nil)
    }
    
    func reloadWeather() {
        let weather = weatherAPI.fetchWeatherCondition()
        weatherImage.image = UIImage(named: getImageName(for: weather))
        weatherImage.tintColor = getImageColor(for: weather)
    }
}

protocol WeatherViewDelegate: AnyObject {
    func closeWeather()
    func reloadWeather()
}
```
に変更

### 現状
Deinitializeされない(メモリリーク?)

2023-09-07 03:15 UTC, laiug787 commented
ご確認お願いいたします。

2023-09-07 07:34 UTC, macneko-ayu commented
WIPになっているのですが、コメント入れちゃいますね。
Delegateの理解が違ってそうです。
いまの状態ではViewController内の処理を無駄に複雑にしただけになっています。
ios-trainingのドキュメントに

> Delegateというワードを良く目にすると思います。 日本語では委譲と呼ばれます

と記載されているように、処理を移譲することが目的なので、登場人物はWhatherViewControllerとそれ以外のものになります。

2023-09-07 07:57 UTC, laiug787 commented
@macneko-ayu 

> いまの状態ではViewController内の処理を無駄に複雑にしただけになっています。

確かにそう感じます。Action内に`delegate?.`を含まなければDelegateを用いない書き方でスッキリするのですが、
いかんせん、Delegateを用いる方法がわかりません。(調査中)

2023-09-07 08:04 UTC, macneko-ayu commented
> Delegateパターンを使い、APIから天気予報を受け取る

これがヒントかなぁと思います。
Delegateパターンの実装自体はいいと思うので、解決すべき課題は使い方ですね

2023-09-07 08:09 UTC, laiug787 commented
@macneko-ayu 
修正してみます。
もし間違っていたら、悪化していたら
ご指摘のほどよろしくお願いいたします🙇

2023-09-07 09:10 UTC, laiug787 commented
UITableViewControllerを意識して修正しました。

2023-09-07 16:42 UTC, ykws commented on WhetherApp/WeatherViewController.swift
>          let weather = weatherAPI.fetchWeatherCondition()
> Delegateパターンを使い、APIから天気予報を受け取る

この部分が API から天気予報を受け取る部分なので、この処理を委譲して欲しいです。
疑似コードですが、次のような形で受け取れるようにしたいということです。

```swift
    func reloadWeather() {
        weatherAPI.fetchWeatherCondition() // 処理を委譲し、結果は Delegate で受け取る
    }
}

extension WeatherViewController: 天気予報を受け取るDelegate {
    func 天気予報を受け取る(let weather: Weather) {
        // 受け取った天気予報で View を更新する
```

2023-09-07 16:42 UTC, ykws commented on WhetherApp/WeatherViewDelegate.swift
> +    func reloadWeather()
> UITableViewControllerを意識して修正しました。

UITableViewDelegate の API 仕様を見ると、命名など参考になると思います。

https://developer.apple.com/documentation/uikit/uitableviewdelegate

2023-09-08 03:16 UTC, laiug787 commented on WhetherApp/WeatherViewDelegate.swift
> +    func reloadWeather()
ありがとうございます。

2023-09-08 03:20 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
>          let weather = weatherAPI.fetchWeatherCondition()
ありがとうございます。
可能な限り意図を咀嚼して、修正しました。

2023-09-08 03:21 UTC, laiug787 commented
修正しました。

2023-09-08 06:55 UTC, novr requested changes

2023-09-08 06:55 UTC, novr commented on WhetherApp/WeatherViewDelegate.swift
> +protocol WeatherViewDelegate: AnyObject {
[must] WeatherViewDelegateの命名が違います
`HogeDelegate`は`Hoge`が使います
WeatherRepositoryがfetchWeatherConditionの結果を通知する処理を委譲するので
定義するメソッドも違う名前になります

2023-09-08 06:55 UTC, novr commented on WhetherApp/WeatherViewController.swift
> +    private var repository = WeatherRepository()
[imo] WeatherRepositoryProtocolが定義されているので、型はWeatherRepositoryProtocolのがいいです

2023-09-08 06:55 UTC, novr commented on WhetherApp/WeatherRepository.swift
> +    func close() {
[must] closeはWeatherRepositoryで処理する事がないので不要です

2023-09-08 07:13 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    func close() {
[621f46c](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/4/commits/621f46ced570ce141245791741e4a026e312eab1)
修正しました。

2023-09-08 07:28 UTC, macneko-ayu requested changes
Delegateの理解が違ってそうなので、コメントを見てもらって修正をお願いします🙏

2023-09-08 07:28 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
コードにコメントつけるのが難しかったので、ファイルに対して指摘します。

WeatherRepositoryがViewのことを知っているので、責務分離ができていない印象があります。
WeatherRepositoryの役割をどう定義するか次第ではあるのですが、通信とViewが密接になっているとそもそもクラスやファイルを分割する意味が薄くなります（数百行のファイルを分割するというのとは話が別）。
私のイメージではWeatherRepositoryは通信を責務とするので、このSessionでは `YumemiWeather.fetchWeatherCondition()` の結果をdelegateに流すことになります。

2023-09-08 07:28 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +    weak var delegate: WeatherViewDelegate?
結論：WeatherRepositoryProtocolにdelegateプロパティを移しましょう

理由：
delegateの移譲先を必ず設定する必要がありますが、現状は実装した人にしかそれがわからない状態になっています。
ところで、WeatherRepositoryProtocolにfetchWeatherCondition()というメソッドが定義されています。
これはWeatherRepositoryProtocolに準拠するクラスや構造体は、fetchWeatherCondition()メソッドを実装しなければならないという制約を設けているということです。
同じようにdelegateも前述したように必ず指定しないといけないプロパティなので、WeatherRepositoryProtocolに移す必要があります

2023-09-08 07:28 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +        delegate?.reloadButtonTapped(weather)
別の指摘でも記載しましたが、このRepositoryの責務は通信した結果を移譲先に渡すことなので、値だけを渡すインターフェースに変更が必要だと思います

2023-09-08 07:28 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +        delegate?.closeButtonTapped()
このメソッドはResitoryの責務ではないと思います

2023-09-08 07:28 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +    private var repository = WeatherRepository()
WeatherRepositoryのインスタンスを保持せずに、protocolをプロパティとして持ちます。
そうすることで、テスト時にprotocolの実装クラスを差し替えて挙動を変えられたりします。

2023-09-08 07:28 UTC, macneko-ayu commented on WhetherApp/WeatherViewDelegate.swift
> +protocol WeatherViewDelegate: AnyObject {
この記事がdelegateがどういったものかや命名規則などが書かれているので、一読して修正をお願いしたいです。
AppleのAPIドキュメントも参考になります。
https://dev.classmethod.jp/articles/delegate-protocol-writing-and-concepts/

2023-09-08 07:37 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +        delegate?.closeButtonTapped()
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/4#discussion_r1319462182
こちらで修正しました。

2023-09-08 08:16 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +    private var repository = WeatherRepository()
> protocolの実装クラスを差し替えて挙動を変えられる

なるほど

2023-09-08 10:58 UTC, laiug787 commented on WhetherApp/WeatherViewDelegate.swift
> +protocol WeatherViewDelegate: AnyObject {
[cc6d765](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/4/commits/cc6d7655138589ec5254997b38a6d8cf59df03ee)
修正しました。

2023-09-08 10:59 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +    private var repository = WeatherRepository()
[2ccd2fe](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/4/commits/2ccd2fed667e1ce8f397d9223cc4290cfff214f2)
修正しました。

2023-09-08 11:00 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +    private var repository = WeatherRepository()
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/4#discussion_r1319708690
こちらで修正しました。

2023-09-11 01:12 UTC, macneko-ayu commented on WhetherApp/WeatherViewController.swift
> +        print("Deinitialize WeatherViewController")
![must-badge](https://img.shields.io/badge/review-must-red.svg)
現状のコードではdeinit時のprintが実行されていません。
どこかでメモリリークしている可能性があるので、調査して修正をお願いします。
ヒントはどこかでデグレしています。

2023-09-11 01:12 UTC, macneko-ayu commented on WhetherApp/WeatherRepositoryDelegate.swift
> +    func reloadButtonTapped(_ weather: WeatherCondition)
![must-badge](https://img.shields.io/badge/review-must-red.svg)
繰り返しになりますが、現状のdelegateメソッドの命名規則がAppleの命名に沿っていません。
[課題のヒント部分](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md)や以下の記事を参照して、命名を変更してください。
https://dev.classmethod.jp/articles/delegate-protocol-writing-and-concepts/

2023-09-11 01:18 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +        print("Deinitialize WeatherViewController")
調査します。

2023-09-11 01:22 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +        print("Deinitialize WeatherViewController")
WeatherRepository内の`weak var delegate`でした。
[111b353](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/4/commits/111b353e21f484f5d4a1a3252c9a415e50a3b49d)
ありがとうございます。
修正いたしました。

2023-09-11 01:25 UTC, laiug787 commented on WhetherApp/WeatherRepositoryDelegate.swift
> +    func reloadButtonTapped(_ weather: WeatherCondition)
度々ありがとうございます。
WeatherRepositoryDelegateのメソッドの命名を見直します。

2023-09-11 03:30 UTC, laiug787 commented
修正いたしました。

2023-09-11 07:08 UTC, ykws approved these changes
よく対応されていると思いました 👍

2023-09-11 07:08 UTC, ykws commented on WhetherApp/WeatherRepositoryDelegate.swift
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

Xcode で Apple の UIWindowSceneDelegate や UIApplicationDelegate に対して Jump to Definition するとそれぞれ UIWindowScene や UIApplication と同じファイルで定義されていることが確認できます。（それぞれ AppDelegate, SceneDelegate に参照があります）
WeatherRepositoryDelegate は WeatherRepository と同じファイルで定義すると驚きが少ないです。

2023-09-11 07:08 UTC, ykws commented on WhetherApp/WeatherViewController.swift
> +// MARK: Extensions
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
上も extensions なので、 Delegate のコメントとレベル合わせるなら Private がコメントとしては相応しそうです。

```suggestion
// MARK: Private
```

2023-09-11 07:45 UTC, macneko-ayu approved these changes
ペアワーク、ありがとうございました！
根気強く対応していただいて、ありがとうございました

2023-09-11 08:11 UTC, laiug787 commented on WhetherApp/WeatherViewController.swift
> +// MARK: Extensions
なんとコメントすれば良いのか迷っていました。
ご指摘ありがとうございます。

2023-09-11 08:15 UTC, laiug787 commented on WhetherApp/WeatherRepositoryDelegate.swift
```swift
protocol ***Delegate {
   func ***()
}
```
メソッド名がどこに由来するのか分からなかったため
上記のように揃えておくのは学びになりました。

2023-09-11 08:20 UTC, laiug787 commented
@macneko-ayu ペアワーク、ありがとうございました。振り返ってみても、一人では解決できなさそうな課題で、Delegateパターンの用法を雰囲気でも掴むことができました。度重なるレビューをありがとうございます🙇

2023-09-11 14:22 UTC, novr approved these changes

2023-09-11 14:22 UTC, novr commented on WhetherApp/WeatherRepositoryDelegate.swift
> +//  WeatherViewDelegate.swift
[nits] 
```suggestion
//  WeatherRepositoryDelegate.swift
```

2023-09-12 01:24 UTC, merged