[WIP] Session 7: Codable
laiug787/ios-training-laiug787-WeatherApp pull request #7
Opened 2023-09-11 09:57 UTC by laiug787

## 概要
・APIにリクエストするstringをstruct由来で作成する(Encodableを利用する)

### 課題URL
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Codable.md

### 変更点概略
```swift
struct WeatherRequest: Encodable {
    var area: String
    var date: Date
    
    enum CodingKeys: String, CodingKey {
        case area
        case date
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(area, forKey: .area)
        try container.encode(date.yyyyMMddTHHmmssZZZZZ, forKey: .date)
    }
    
    func encodeToString() -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = .prettyPrinted
        encoder.keyEncodingStrategy = .convertToSnakeCase

        do {
            let jsonData = try encoder.encode(self)
            guard let string = String(data: jsonData, encoding: .utf8) else {
                fatalError("Fail to convert Data to String")
            }
            return string
        } catch {
            fatalError("Fail to convert WeatherRequest to String")
        }
    }
}

private extension DateFormatter {
    static var yyyyMMddTHHmmssZZZZZ: DateFormatter {
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale(identifier: "ja_JP")
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
        return dateFormatter
    }
}

private extension Date {
    var yyyyMMddTHHmmssZZZZZ: String {
        DateFormatter.yyyyMMddTHHmmssZZZZZ.string(from: self)
    }
}
```
を追加

2023-09-14 02:18 UTC, macneko-ayu requested changes

2023-09-14 02:18 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +            let request = WeatherRequest(area: "Tokyo", date: .now)
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
リクエストするときのパラメータは基本的に外からRepositoryに渡されるものなので、そのようなIFにしておきたいですね

2023-09-14 02:18 UTC, macneko-ayu commented on WhetherApp/WeatherRequest.swift
> +private extension DateFormatter {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`JSONEncoder.dateEncodingStrategy` を利用すると、42〜55行目までの処理が不要になるはずです。
https://developer.apple.com/documentation/foundation/jsonencoder/2895363-dateencodingstrategy

2023-09-14 02:18 UTC, macneko-ayu commented on WhetherApp/WeatherRequest.swift
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
Encoderを自前で用意することで冗長になっていると感じました

2023-09-14 02:18 UTC, macneko-ayu commented on WhetherApp/WeatherRequest.swift
> +struct WeatherRequest: Encodable {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
`WeatherRequest` という命名は、内部でリクエストを行っていると誤認識を与える可能性があるので、ふさわしくないと感じました。
`WeatherRequestParameter`  あたりが妥当に感じます

2023-09-14 02:30 UTC, laiug787 commented
mainブランチにリベースしました

2023-09-14 02:31 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +            let request = WeatherRequest(area: "Tokyo", date: .now)
Viewから受け取れるよう直してみます

2023-09-14 03:31 UTC, laiug787 commented on WhetherApp/WeatherRequest.swift
> +struct WeatherRequest: Encodable {
[c51b857](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/7/commits/c51b8575fd3b068894583dde147339b789b17c5c)
WeatherRequestDataにしました。

2023-09-14 03:33 UTC, laiug787 commented on WhetherApp/WeatherRequest.swift
> +private extension DateFormatter {
[88d9818](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/7/commits/88d981818cb5ec22de5f6500599248eff2c57393)
`encoder.dateEncodingStrategy = .iso8601`の利用で、コードがスッキリしました。

2023-09-14 03:33 UTC, laiug787 commented on WhetherApp/WeatherRequest.swift
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/7#discussion_r1325313613
こちらで修正しました。

2023-09-14 03:46 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +            let request = WeatherRequest(area: "Tokyo", date: .now)
[21e91e6](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/7/commits/21e91e68466079f34c65048f50b774bb759ea0bd)
こちらで、修正しました。

2023-09-14 03:54 UTC, laiug787 commented
ファイルの整理をしたので、Session 7の次にフォルダ構成についてレビューを頂きたいです。
https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/8

2023-09-14 05:26 UTC, macneko-ayu commented on WhetherApp/WeatherRequest.swift
> +struct WeatherRequest: Encodable {
`~Data` って私も使いがちなんですが、そもそも全部Dataなので、その型が表現したい内容に沿ったより具体的な命名を考えてほしいです

2023-09-14 05:56 UTC, laiug787 commented on WhetherApp/WeatherRequest.swift
> +struct WeatherRequest: Encodable {
>そもそも全部Dataなので

確かにそうですね、
ここは、アドバイスに従ってWeatherRequestParameterにしてみます。

2023-09-14 06:00 UTC, macneko-ayu requested changes
ヘッダー名だけmustです

2023-09-14 06:00 UTC, macneko-ayu commented on WhetherApp/WeatherRequestData.swift
> +//  WeatherRequest.swift
![must-badge](https://img.shields.io/badge/review-must-red.svg)
ヘッダー名と型名が一致していません

2023-09-14 06:00 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +        let data = Data(string.utf8)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
StringからDataに変換するメソッドが存在するので、それを使ったほうが直感的ですね

```swift
        guard let data = string.data(using: .utf8) else {
            throw WeatherError.unknown // Errorは適当です
        }
```

2023-09-14 06:00 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +        return String(decoding: jsonData, as: UTF8.self)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
以下のイニシャライザのほうが一般的かもしれないです

```swift
// String? を返すのでunwrapするなどのケアが必要
String(data: jsonData, encoding: .utf8)
```

2023-09-14 06:00 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +            let weatherRequestData = WeatherRequestData(area: area, date: date)
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
dataがついた変数が並んでいて、パッと見わかりづらいですね…

2023-09-14 06:01 UTC, laiug787 commented on WhetherApp/WeatherRequest.swift
> +struct WeatherRequest: Encodable {
[3d1fd50](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/9/commits/3d1fd50748364890f3155e0d1f0fc87e8126501a)
Session 8 の方で修正しました。

2023-09-14 06:45 UTC, laiug787 commented on WhetherApp/WeatherRequestData.swift
> +//  WeatherRequest.swift
[801985b](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/9/commits/801985ba973faf15ec74bb8842b952d50d03cc22)
Session 8で修正しました

2023-09-14 06:46 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +        let data = Data(string.utf8)
[ad57da9](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/9/commits/ad57da92321711d3685bac70683bbd6e8b68b7c7)
Session 8で修正しました

2023-09-14 06:46 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +        return String(decoding: jsonData, as: UTF8.self)
[ad57da9](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/9/commits/ad57da92321711d3685bac70683bbd6e8b68b7c7)
Session 8で修正しました

2023-09-14 06:46 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +            let weatherRequestData = WeatherRequestData(area: area, date: date)
[ad57da9](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/9/commits/ad57da92321711d3685bac70683bbd6e8b68b7c7)
Session 8で書き直しました

2023-09-14 07:12 UTC, macneko-ayu approved these changes
Session8 で修正されていました！

2023-09-14 07:14 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +    private func encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String {
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
メソッドの定義を見ないと戻り値がわからないので、メソッド名から連想できるようになっているといいと思いました

2023-09-14 07:15 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +    private func decodeWeatherData(_ string: String) throws -> WeatherData {
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
メソッドの定義を見ないと戻り値がわからないので、メソッド名から連想できるようになっているといいと思いました

2023-09-14 07:20 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    private func encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String {
`encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String`
`encodeWeatherRequestDataToString(_ data: WeatherRequestData) throws -> String`
`encode(WeatherRequestData data: WeatherRequestData) throws -> String`
`encodeToString(WeatherRequestData data: WeatherRequestData) throws -> String`
で迷ってました。先ほど上から3番目に書き直してました。

2023-09-14 07:21 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    private func encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String {
まだ、悩んでます。

2023-09-14 07:22 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    private func encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String {
上から2番目と4番目で

2023-09-14 07:23 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    private func decodeWeatherData(_ string: String) throws -> WeatherData {
承知しました。

2023-09-14 23:53 UTC, macneko-ayu commented on WhetherApp/WeatherRepository.swift
> +    private func encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String {
私が変更するなら以下かなぁ…。
人によって意見がわかれそうですね 😇 
`encodeToString(from data: WeatherRequestData) throws -> String`

2023-09-14 23:54 UTC, macneko-ayu commented
命名の部分はnextなので、無視しちゃっていいですよ！
私も正解を知っているわけではないので🙏

2023-09-15 03:58 UTC, laiug787 commented
@macneko-ayu レビュー、ありがとうございます。nextで改善します

2023-09-15 03:58 UTC, laiug787 commented on WhetherApp/WeatherRepository.swift
> +    private func encodeWeatherRequestData(_ data: WeatherRequestData) throws -> String {
fromはいいですね

2023-09-15 03:58 UTC, merged