[WIP] Session 8: NotificationCenter
laiug787/ios-training-laiug787-WeatherApp pull request #9
Opened 2023-09-12 07:00 UTC by laiug787

2023-09-14 09:28 UTC, novr requested changes
エラー表示中にバックグラウンドから戻ると、天気が更新されてしまいます

また、エラー表示中の更新で再度エラーが発生するとconsoleに以下のメッセージが表示されます
ライフサイクル違反なのででないように修正しましょう
```log
2023-09-14 18:23:21.172445+0900 WhetherApp[32542:11359867] [Presentation] Attempt to present <UIAlertController: 0x13b839000> on <WhetherApp.WeatherViewController: 0x13740a490> (from <WhetherApp.WeatherViewController: 0x13740a490>) which is already presenting <UIAlertController: 0x13b827c00>.
```
![Simulator Screenshot - iPhone 14 Pro - 2023-09-14 at 18 23 06](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/assets/47618299/0cc5b240-34cd-4be1-9e99-a9e3d5992f25)

2023-09-14 09:57 UTC, laiug787 commented
@novr 気づきませんでした。ありがとうございます。修正します。

2023-09-15 04:13 UTC, laiug787 commented
mainにrebaseしました

2023-09-15 04:14 UTC, laiug787 commented
@novr 
> エラー表示中にバックグラウンドから戻ると、天気が更新されてしまいます

[ee21cad](https://github.com/yumemi-inc/ios-training-laiug787-WhetherApp/pull/9/commits/ee21cad65d8494fd5f11671e741e2935dc6337de)
こちらで修正しました。

2023-09-15 05:11 UTC, novr commented on WhetherApp/Controllers/WeatherViewController.swift
> +    private var isAlertVisible: Bool = false
[imo] ViewControllerがpresentしているViewControllerは[presentedViewController](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621407-presentedviewcontroller)で取得できます
Alertかどうかは`is UIAlertController`でも判断できます

2023-09-15 05:47 UTC, laiug787 commented on WhetherApp/Controllers/WeatherViewController.swift
> +    private var isAlertVisible: Bool = false
ありがとうございます。
修正します。

2023-09-15 08:36 UTC, laiug787 commented on WhetherApp/Controllers/WeatherViewController.swift
> +    private var isAlertVisible: Bool = false
@novr 
[249d05b](https://github.com/laiug787/ios-training-laiug787-WeatherApp/pull/10/commits/249d05b2497be1253c857afec2a9b04f7699d003) 
Session 9の方で修正しました。

2023-09-28 06:40 UTC, novr commented on WhetherApp/Controllers/WeatherViewController.swift
> +    private var isAlertVisible: Bool = false
@laiug787 ReviewRequest欄に残ってしまうので、Reviewersからnovrを外すか、PRのmerge or closeをお願いします

2023-10-03 07:55 UTC, laiug787 commented on WhetherApp/Controllers/WeatherViewController.swift
> +    private var isAlertVisible: Bool = false
気づくのに遅くなってすみません。承知いたしました。

2023-10-03 07:55 UTC, merged